#version: '3.8'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: genifast
      POSTGRES_DB: genifast
    networks:
      - es-net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  fe_react:
    container_name: fe-react-container
    build: ./react-fe
    ports:
      - "5173:5173"
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  be_golang:
    container_name: be-golang-container
    build: ./go-be
    ports:
      - "8080:8080"
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  be_java:
    container_name: be-java-container
    build: ./be-java
    ports:
      - "8098:8098" #fix from 8089
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

  be_python:
    container_name: be-python-container
    build: .
    ports:
      - "8000:8000"
    networks:
      - es-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: always

networks:
  es-net:
    driver: bridge

volumes:
  es_data:
  postgres_data: